### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by subnetmarco** [faye/faye-cluster-node#3]
Can you publish it on npm?

**Comment by jcoglan** [comment]
Not yet, it's nowhere near ready. It's still at the experimental stage, and I've not had time to work on it for a while.

**Comment by jcoglan** [comment]
I think it's clear that this is not going to happen any time soon. I've not worked on this for a long time, it was just a spike. The intention was to build something that any user could build on top of Faye, without requiring internal changes.

There is not a lot of code here; if you ever plan on publishing a module like this, please do not publish my code since I have no intention of maintaining this. You should either rewrite it, or import what's here into your own module that you plan to maintain.
